/**
 * `npm run content:seed` — writes supabase/seed/scenarios.sql from the bundled
 * scenario library so the database copy never drifts from the app copy.
 *
 * The generated file is idempotent: rerunning it against a live project
 * upserts every scenario by id.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ALL_SCENARIOS } from '../src/content';
import { formatIssues, validateLibrary } from '../src/engine/validate';
import type { Scenario } from '../src/domain/scenario';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'supabase', 'seed', 'scenarios.sql');

const issues = validateLibrary(ALL_SCENARIOS);
if (issues.length) {
  console.error(`Refusing to generate seed — ${issues.length} issue(s):\n${formatIssues(issues)}`);
  process.exit(1);
}

function quote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function enumArray(values: string[], type: string): string {
  if (!values.length) return `'{}'::${type}[]`;
  return `array[${values.map(quote).join(', ')}]::${type}[]`;
}

function textArray(values: string[]): string {
  if (!values.length) return `'{}'::text[]`;
  return `array[${values.map(quote).join(', ')}]::text[]`;
}

function row(scenario: Scenario): string {
  return [
    '  (',
    `    ${quote(scenario.id)},`,
    `    ${quote(scenario.kind)}::public.scenario_kind,`,
    `    ${quote(scenario.title)},`,
    `    ${quote(scenario.summary)},`,
    `    ${quote(scenario.setting)},`,
    `    ${enumArray(scenario.role_relevance, 'public.leadership_role')},`,
    `    ${enumArray(scenario.rank_relevance, 'public.scout_rank')},`,
    `    ${textArray(scenario.primary_dimensions)},`,
    `    ${scenario.estimated_minutes},`,
    `    ${quote(JSON.stringify(scenario.branching_tree))}::jsonb`,
    '  )',
  ].join('\n');
}

const sql = `-- Generated by \`npm run content:seed\`. Do not edit by hand.
-- Source: src/content/*. ${ALL_SCENARIOS.length} scenarios.

insert into public.scenarios (
  id, kind, title, summary, setting,
  role_relevance, rank_relevance, primary_dimensions,
  estimated_minutes, branching_tree
) values
${ALL_SCENARIOS.map(row).join(',\n')}
on conflict (id) do update set
  kind = excluded.kind,
  title = excluded.title,
  summary = excluded.summary,
  setting = excluded.setting,
  role_relevance = excluded.role_relevance,
  rank_relevance = excluded.rank_relevance,
  primary_dimensions = excluded.primary_dimensions,
  estimated_minutes = excluded.estimated_minutes,
  branching_tree = excluded.branching_tree,
  is_published = true;
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, sql, 'utf8');
console.log(`Wrote ${outPath} (${ALL_SCENARIOS.length} scenarios, ${sql.length} bytes)`);
