-- Patrol Leadership Simulator — initial schema.
--
-- Auth model: self sign-up with a troop join code. A scout signs up through
-- Supabase Auth, then calls register_scout() with the code their troop gave
-- them. The troops table is never readable directly, so join codes cannot be
-- enumerated -- the only way in is the security-definer function below.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type public.scout_rank as enum (
  'scout',
  'tenderfoot',
  'second_class',
  'first_class',
  'star',
  'life',
  'eagle'
);

create type public.leadership_role as enum ('PL', 'APL', 'SPL');

create type public.scenario_kind as enum ('calibration', 'training');

-- ---------------------------------------------------------------------------
-- Troops and patrols
-- ---------------------------------------------------------------------------

create table public.troops (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  -- Short code handed out by the troop. Case-insensitively unique.
  join_code text not null,
  created_at timestamptz not null default now()
);

create unique index troops_join_code_key on public.troops (upper(join_code));

-- Created now, no logic yet. Needed for companion mode.
create table public.patrols (
  id uuid primary key default gen_random_uuid(),
  troop_id uuid not null references public.troops (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (troop_id, name)
);

-- ---------------------------------------------------------------------------
-- Scouts
-- ---------------------------------------------------------------------------

-- One row per authenticated user. id is the auth user id, which keeps every
-- RLS policy in this file down to a single comparison.
create table public.scouts (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null check (length(btrim(name)) between 1 and 60),
  rank public.scout_rank not null default 'scout',
  current_role public.leadership_role not null default 'PL',
  troop_id uuid references public.troops (id) on delete set null,
  -- Nullable until companion mode assigns scouts to patrols.
  patrol_id uuid references public.patrols (id) on delete set null,
  created_at timestamptz not null default now()
);

create index scouts_troop_id_idx on public.scouts (troop_id);

-- ---------------------------------------------------------------------------
-- Skill profiles
-- ---------------------------------------------------------------------------

-- Scores are 0-100 with 50 as the neutral starting point. calibrated_at is
-- null until the scout finishes the assessment.
create table public.skill_profiles (
  scout_id uuid primary key references public.scouts (id) on delete cascade,
  communication numeric(5, 1) not null default 50 check (communication between 0 and 100),
  conflict_resolution numeric(5, 1) not null default 50 check (conflict_resolution between 0 and 100),
  delegation numeric(5, 1) not null default 50 check (delegation between 0 and 100),
  planning numeric(5, 1) not null default 50 check (planning between 0 and 100),
  initiative numeric(5, 1) not null default 50 check (initiative between 0 and 100),
  calibrated_at timestamptz,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Scenarios
-- ---------------------------------------------------------------------------

-- Content table. Rows are seeded from the app's bundled library (see
-- supabase/seed/scenarios.sql, generated by `npm run content:seed`) and can be
-- updated without an app release.
create table public.scenarios (
  id text primary key,
  kind public.scenario_kind not null default 'training',
  title text not null,
  summary text not null default '',
  setting text not null default '',
  role_relevance public.leadership_role[] not null default '{}',
  rank_relevance public.scout_rank[] not null default '{}',
  primary_dimensions text[] not null default '{}',
  estimated_minutes integer not null default 3 check (estimated_minutes > 0),
  branching_tree jsonb not null,
  is_published boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint scenarios_dimensions_valid check (
    primary_dimensions <@ array[
      'communication',
      'conflict_resolution',
      'delegation',
      'planning',
      'initiative'
    ]::text[]
  ),
  constraint scenarios_tree_shape check (
    branching_tree ? 'root'
    and branching_tree ? 'nodes'
    and (branching_tree ->> 'version') = '1'
  )
);

create index scenarios_kind_idx on public.scenarios (kind) where is_published;

-- ---------------------------------------------------------------------------
-- Attempts
-- ---------------------------------------------------------------------------

create table public.scenario_attempts (
  id uuid primary key default gen_random_uuid(),
  scout_id uuid not null references public.scouts (id) on delete cascade,
  -- Attempts survive a scenario being retired from the content table.
  scenario_id text not null references public.scenarios (id) on delete restrict,
  choices_made jsonb not null default '[]'::jsonb,
  score_deltas jsonb not null default '{}'::jsonb,
  completed_at timestamptz not null default now()
);

create index scenario_attempts_scout_idx on public.scenario_attempts (scout_id, completed_at desc);

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger skill_profiles_touch
  before update on public.skill_profiles
  for each row execute function public.touch_updated_at();

create trigger scenarios_touch
  before update on public.scenarios
  for each row execute function public.touch_updated_at();

-- Every scout gets a profile at baseline the moment the row exists, so the app
-- never has to handle a scout without one.
create or replace function public.create_skill_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.skill_profiles (scout_id)
  values (new.id)
  on conflict (scout_id) do nothing;
  return new;
end;
$$;

create trigger scouts_create_profile
  after insert on public.scouts
  for each row execute function public.create_skill_profile();

-- ---------------------------------------------------------------------------
-- Sign-up: join a troop with a code
-- ---------------------------------------------------------------------------

-- Called once, right after the auth sign-up, by the scout themselves. Security
-- definer so it can read troops (which nobody can select directly) without
-- leaking join codes. Raises rather than returning null so the client cannot
-- tell "bad code" apart from any other failure by timing alone.
create or replace function public.register_scout(
  p_name text,
  p_rank public.scout_rank,
  p_role public.leadership_role,
  p_join_code text
)
returns public.scouts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_troop_id uuid;
  v_scout public.scouts;
begin
  if auth.uid() is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;

  select id into v_troop_id
  from public.troops
  where upper(join_code) = upper(btrim(p_join_code));

  if v_troop_id is null then
    raise exception 'unknown troop code' using errcode = 'P0002';
  end if;

  insert into public.scouts (id, name, rank, current_role, troop_id)
  values (auth.uid(), btrim(p_name), p_rank, p_role, v_troop_id)
  on conflict (id) do update
    set name = excluded.name,
        rank = excluded.rank,
        current_role = excluded.current_role,
        troop_id = excluded.troop_id
  returning * into v_scout;

  return v_scout;
end;
$$;

revoke all on function public.register_scout(text, public.scout_rank, public.leadership_role, text) from public;
grant execute on function public.register_scout(text, public.scout_rank, public.leadership_role, text) to authenticated;

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.troops enable row level security;
alter table public.patrols enable row level security;
alter table public.scouts enable row level security;
alter table public.skill_profiles enable row level security;
alter table public.scenarios enable row level security;
alter table public.scenario_attempts enable row level security;

-- Helper: the troop the current user belongs to. Security definer so the
-- policies below do not recurse through the scouts policy.
create or replace function public.current_troop_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select troop_id from public.scouts where id = auth.uid();
$$;

-- Troops: a scout can see the troop they are in. No one can select by code,
-- so codes stay unguessable-by-listing.
create policy troops_read_own on public.troops
  for select to authenticated
  using (id = public.current_troop_id());

-- Patrols: readable within your own troop. No writes yet (companion mode).
create policy patrols_read_own_troop on public.patrols
  for select to authenticated
  using (troop_id = public.current_troop_id());

-- Scouts: full control of your own row.
create policy scouts_read_self on public.scouts
  for select to authenticated
  using (id = auth.uid());

-- Scouts: read-only visibility of troop mates, for rosters later. Names and
-- ranks only in practice -- there is nothing sensitive on this table.
create policy scouts_read_troop on public.scouts
  for select to authenticated
  using (troop_id is not null and troop_id = public.current_troop_id());

create policy scouts_insert_self on public.scouts
  for insert to authenticated
  with check (id = auth.uid());

create policy scouts_update_self on public.scouts
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- Skill profiles: strictly your own. A scout's scores are not troop-visible.
create policy skill_profiles_read_self on public.skill_profiles
  for select to authenticated
  using (scout_id = auth.uid());

create policy skill_profiles_insert_self on public.skill_profiles
  for insert to authenticated
  with check (scout_id = auth.uid());

create policy skill_profiles_update_self on public.skill_profiles
  for update to authenticated
  using (scout_id = auth.uid())
  with check (scout_id = auth.uid());

-- Scenarios: content is readable by any signed-in scout. Writes are service
-- role only (the seed script), so nobody can edit the curriculum from a phone.
create policy scenarios_read_published on public.scenarios
  for select to authenticated
  using (is_published);

-- Attempts: strictly your own.
create policy attempts_read_self on public.scenario_attempts
  for select to authenticated
  using (scout_id = auth.uid());

create policy attempts_insert_self on public.scenario_attempts
  for insert to authenticated
  with check (scout_id = auth.uid());
